### ISSUE TITLE
Fails to build on MacOS

### ISSUE THREAD

**Issue by mchaliadzinau** [coderedart/egui_overlay#8]
Cannot build latest version. Is `cmake` really a requirement? 😭 
```
error: failed to run custom build command for `glfw-sys-passthrough v4.0.3+3.3.5`

Caused by:
  process didn't exit successfully: `/Users/mikalaichaliadzinau/Projects/SRCs/others/egui-ui/target/debug/build/glfw-sys-passthrough-747d6d24e0d81238/build-script-build` (exit status: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_aarch64-apple-darwin = None
  CMAKE_TOOLCHAIN_FILE_aarch64_apple_darwin = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_aarch64-apple-darwin = None
  CMAKE_GENERATOR_aarch64_apple_darwin = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_aarch64-apple-darwin = None
  CMAKE_PREFIX_PATH_aarch64_apple_darwin = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_aarch64-apple-darwin = None
  CMAKE_aarch64_apple_darwin = None
  HOST_CMAKE = None
  CMAKE = None
  running: cd "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui-ui/target/debug/build/glfw-sys-passthrough-53d6cf408a3bcc1b/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/Users/mikalaichaliadzinau/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glfw-sys-passthrough-4.0.3+3.3.5/." "-DCMAKE_OSX_ARCHITECTURES=arm64" "-DGLFW_BUILD_EXAMPLES=OFF" "-DGLFW_BUILD_TESTS=OFF" "-DGLFW_BUILD_DOCS=OFF" "-DCMAKE_INSTALL_LIBDIR=lib" "-DGLFW_BUILD_WAYLAND=OFF" "-DCMAKE_INSTALL_PREFIX=/Users/mikalaichaliadzinau/Projects/SRCs/others/egui-ui/target/debug/build/glfw-sys-passthrough-53d6cf408a3bcc1b/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -arch arm64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -arch arm64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -arch arm64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Debug"

  --- stderr
  thread 'main' panicked at '
  failed to execute command: No such file or directory (os error 2)
  is `cmake` not installed?

  build script failed, must exit now', /Users/mikalaichaliadzinau/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Comment by coderedart** [comment]
I don't have a Mac, so this is beyond me. But what is the problem with installing cmake? Glfw needs cmake to build https://www.glfw.org/docs/latest/compile_guide.html#compile_cmake :(

**Comment by mchaliadzinau** [comment]
> I don't have a Mac, so this is beyond me.

Got it... this is unfortunate 😭 

Installing cmake helped to compile glfw-sys-passthrough but now it failing on egui_window_glfw_passthrough.

Just in case it somehow clicks for you or someone else stumbling upon this issue I leave the output here:
```
cargo run --example hello
   Compiling bytemuck_derive v1.4.0
   Compiling zerocopy-derive v0.3.2
   Compiling thiserror-impl v1.0.38
   Compiling tracing-attributes v0.1.23
   Compiling approx v0.4.0
   Compiling glfw-sys-passthrough v4.0.3+3.3.5
   Compiling cgmath v0.18.0
   Compiling bytemuck v1.13.0
   Compiling zerocopy v0.6.1
   Compiling thiserror v1.0.38
   Compiling tracing v0.1.37
   Compiling ecolor v0.22.0
   Compiling emath v0.22.0
   Compiling half v2.2.1
   Compiling epaint v0.22.0
   Compiling three-d-asset v0.5.0
   Compiling egui v0.22.0
   Compiling glfw-passthrough v0.51.1
   Compiling three-d v0.15.0
   Compiling egui_backend v0.4.0
   Compiling egui_render_glow v0.4.0
   Compiling egui_window_glfw_passthrough v0.4.0
   Compiling egui_render_three_d v0.4.0
   Compiling egui_overlay v0.4.0 (/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay)
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/Users/test/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/bin:/Users/test/.nvm/versions/node/v18.13.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/test/.nvm/versions/node/v18.13.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/test/.cargo/bin" VSLANG="1033" ZERO_AR_DATE="1" "cc" "-arch" "arm64" "/var/folders/05/fm0wnzj11_v047_z66njjblc0000gp/T/rustc6g1BZb/symbols.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.12enz4yvca47mfjz.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.13o8pevpktvo4l12.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.14zgngztvi960oj8.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.198tkbd0vfwxltt7.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.19ikyt4j43rt0p3h.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.1b2w5jh6z6id5cru.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.1dbeqk0qucv6e2md.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.1ek2ui9vqwhlht3o.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.1fdt2mm2t0nszjfz.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.1g1y5qirf5n05vjw.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.1gu3pw19aigm4zcn.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.1jitts3d5vodquv8.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.1m66n7aebxid9uz6.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.1o2n89iyb9s1uvr8.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.1thher3rgdshcrcv.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.1uy5fnzbzlgoka8p.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.1wb28jfizfmm48zz.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.1wkftj8o5tsti1xt.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.1wkrqjabmm958xlm.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.1xcfi1kwazb2p2v5.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.20im7lzppa0d1p1s.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.25osc9e0yng0qmzq.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.267j7nc2ath5cgr7.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.26a92n9rglq1szyx.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.26lggrs8kw7iplkq.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.28sezgh7m3m7an9h.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.2bt0yu1p3l48bzyo.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.2dg7uvv9zt0uxiuz.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.2ej5kh0n0xx6de5.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.2f297j6zkak9963j.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.2gj6nzaqhgo8tmfu.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.2oudn59n4g4nrocu.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.2rqp28e0b5trrfp6.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.2s5pvmreve4jvseb.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.2socpnd57h721e4k.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.2vpd2xond3oi3oz8.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.3bq3tvrfhf8gsp1c.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.3bw8yl5lz8hgd63q.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.3cfrhun6uw4i6sm0.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.3js31g07478738nb.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.3kifzmiorpv08m81.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.3kiyez95m5ildseg.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.3kzkfu1qhm8d8047.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.3nw6equ1ewqgnzfl.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.3rhwfvmnp396cynu.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.3s5jgg3v2rlnmeo5.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.3touvdue1gfk6q2o.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.3tpkp59v662u0yna.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.3tym2mcp9kh4tqek.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.3vq3j9j1rmtshzr.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.45ecomdfbpjkvqi5.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.47af4bef0jc9s0ts.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.47c3fkgsmiwqdfg1.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.489rlhiuqa6qu4yu.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.4dmz5g34s6fvfld2.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.4h1x1oixuknibsjp.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.4i9pxyrxpuaemzwh.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.4jm0zh3lait9fb7o.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.4k5cqa94ylgwgr6o.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.4kvkl6jf6lv6sfb4.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.4lib20yd4rkmp0ud.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.4m57owa8ozcr2efv.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.4o4rfr4osp7xszrd.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.4vkqg704p9b7szwf.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.4z45rfp4n6xp1lpy.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.4z5ib1qg1hsh7ztk.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.522y06mwjuo5bfty.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.57qzr50496hua0me.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.59lypcwr8w1utvhd.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.5euoe872cgoskjd2.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.7mv3bed1idiu9jh.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.7nplgtfom7ogitd.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.89c9c6hyurlam0b.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.9b3ng777o740v9n.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.amuzicpayb0uhdp.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.dht4lfat6w28gqu.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.f550jjmwk9oavrx.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.gsxr6l2kj4tzt7f.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.hjf4aiiuvxw1t4n.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.kbgfb5rha0m0m2d.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.omuwjmkkn8r8hsv.rcgu.o" "/Users/test/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.p4vpjqcy3eyfu76.rcgu.o" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.pemsg7icrfle0kf.rcgu.o" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.qwjsfj5jal0kzig.rcgu.o" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.snaconxzz70kb1o.rcgu.o" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.t9xwq52gh0rpgcw.rcgu.o" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.vk3xtfb0uc4uw03.rcgu.o" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.yxy9gufoeqrx3o3.rcgu.o" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586.1hdx70izfe73530m.rcgu.o" "-L" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps" "-L" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/build/glfw-sys-passthrough-772a9a131ee8ba31/out/lib" "-L" "/Users/mikalaichaliadzinau/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libegui_overlay-5a6a625a9c8c3f71.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libegui_window_glfw_passthrough-e49c0f2677b2ef03.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libglfw_passthrough-e99c1fc4ec57475e.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libobjc-b183b6e10a8606ec.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libmalloc_buf-513380925bbf1f79.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libbitflags-ab90ae9dd83462fc.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libegui_render_three_d-3f9869402b4cdaed.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libthree_d-8d03fee33271ec9f.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libthree_d_asset-65e10d7fd952aee6.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libthiserror-2d2b3e32a2babbe0.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libhalf-72b8144bab2212d0.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libzerocopy-2791c5bbd626a6db.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libbyteorder-9245d23a9dfc80e6.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libcgmath-a988b6d6064bcdf8.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libapprox-8aaeac2d9b28bde8.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libnum_traits-8b4781b8cd361b6d.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libegui_render_glow-c27885508ae569a8.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libintmap-20df511a7dfc79fc.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libtracing-a673813a8306ec82.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libpin_project_lite-456cd1d03813701e.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libtracing_core-b468869ae94ec573.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libglow-1653f04a5630b27d.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libegui_backend-9f140d07e25e318f.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libraw_window_handle-38d907e6fb21402b.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libcty-8d36e5e64fdf8527.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libegui-3af05c751e449b7c.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libepaint-c19b618d7ec857ab.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libnohash_hasher-a7de33d1e444e75d.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libecolor-d046d29eb67ec9d2.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libahash-4184e7d3e3eeedbb.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libonce_cell-066834a08699381e.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libab_glyph-eabaefe6305494e9.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libowned_ttf_parser-3453691d3c8f6fb7.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libttf_parser-f781981259db1df8.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libab_glyph_rasterizer-e29d5420623d4885.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libparking_lot-1cce27dcbf002f42.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libparking_lot_core-25f72498df2ea76c.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/liblibc-02f1f3e77d41a054.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libcfg_if-0ec8ce22d83d2462.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libsmallvec-6f7d04298a916d15.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/liblock_api-499d46297d499423.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libscopeguard-f3e62651a1503b47.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libemath-d15232e669751a8e.rlib" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/deps/libbytemuck-e9f10c108542aa27.rlib" "/Users/mikalaichaliadzinau/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libstd-2ca50e2550a11ed4.rlib" "/Users/mikalaichaliadzinau/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libpanic_unwind-a0b15874ec5099e6.rlib" "/Users/mikalaichaliadzinau/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libobject-dca0dfe66399d350.rlib" "/Users/mikalaichaliadzinau/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libmemchr-139c697183de5a45.rlib" "/Users/mikalaichaliadzinau/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libaddr2line-ab400bc75f06afe5.rlib" "/Users/mikalaichaliadzinau/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libgimli-a21366080735b75e.rlib" "/Users/mikalaichaliadzinau/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_demangle-59d24b42d35c0fa1.rlib" "/Users/mikalaichaliadzinau/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libstd_detect-4fc124adb92a6b8c.rlib" "/Users/mikalaichaliadzinau/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libhashbrown-0d73503e669513a0.rlib" "/Users/mikalaichaliadzinau/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libminiz_oxide-1b85702a684cf585.rlib" "/Users/mikalaichaliadzinau/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libadler-a24e569f9e1f1731.rlib" "/Users/mikalaichaliadzinau/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_alloc-76480388111a6770.rlib" "/Users/mikalaichaliadzinau/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libunwind-c16d55155160ec76.rlib" "/Users/mikalaichaliadzinau/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcfg_if-83fe9edd4bff95ef.rlib" "/Users/mikalaichaliadzinau/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/liblibc-c469bd47c3550b1c.rlib" "/Users/mikalaichaliadzinau/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/liballoc-ad1eeb16b5006415.rlib" "/Users/mikalaichaliadzinau/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_core-6886eedc65dccb14.rlib" "/Users/mikalaichaliadzinau/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcore-238d26edba85c951.rlib" "/Users/mikalaichaliadzinau/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins-8940904d1c2f93b4.rlib" "-framework" "Cocoa" "-framework" "OpenGL" "-framework" "IOKit" "-framework" "CoreFoundation" "-framework" "QuartzCore" "-lobjc" "-liconv" "-lSystem" "-lc" "-lm" "-L" "/Users/mikalaichaliadzinau/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "-o" "/Users/mikalaichaliadzinau/Projects/SRCs/others/egui_overlay/target/debug/examples/hello-d58f1d3f89000586" "-Wl,-dead_strip" "-nodefaultlibs"
  = note: Undefined symbols for architecture arm64:
            "_emscripten_set_element_css_size", referenced from:
                _$LT$egui_window_glfw_passthrough..GlfwBackend$u20$as$u20$egui_backend..WindowBackend$GT$::set_window_size::h8b08255b731c4c74 in libegui_window_glfw_passthrough-e49c0f2677b2ef03.rlib(egui_window_glfw_passthrough-e49c0f2677b2ef03.egui_window_glfw_passthrough.06ee8d65-cgu.0.rcgu.o)
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: could not compile `egui_overlay` (example "hello") due to previous error
```

**Comment by Michal-Miko** [comment]
See https://github.com/coderedart/egui_overlay/issues/5, try changing egui_window_glfw_passthrough to version 0.4.1

**Comment by mchaliadzinau** [comment]
Thanks @Michal-Miko!

Now it compiles but fails in runtime. 
```
cargo run --example hello
   Compiling proc-macro2 v1.0.63
   Compiling quote v1.0.29
   Compiling unicode-ident v1.0.9
   Compiling libc v0.2.147
   Compiling parking_lot_core v0.9.8
   Compiling once_cell v1.18.0
   Compiling lock_api v0.4.10
   Compiling ttf-parser v0.19.1
   Compiling syn v1.0.109
   Compiling cmake v0.1.50
   Compiling ahash v0.8.3
   Compiling thiserror v1.0.40
   Compiling raw-window-handle v0.5.2
   Compiling glfw-sys-passthrough v4.0.3+3.3.5
   Compiling tracing-core v0.1.31
   Compiling owned_ttf_parser v0.19.0
   Compiling ab_glyph v0.2.21
   Compiling malloc_buf v0.0.6
   Compiling parking_lot v0.12.1
   Compiling objc v0.2.7
   Compiling syn v2.0.22
   Compiling zerocopy-derive v0.3.2
   Compiling glfw-passthrough v0.51.1
   Compiling zerocopy v0.6.1
   Compiling half v2.3.1
   Compiling bytemuck_derive v1.4.1
   Compiling thiserror-impl v1.0.40
   Compiling tracing-attributes v0.1.26
   Compiling bytemuck v1.13.1
   Compiling tracing v0.1.37
   Compiling emath v0.22.0
   Compiling ecolor v0.22.0
   Compiling three-d-asset v0.5.0
   Compiling epaint v0.22.0
   Compiling egui v0.22.0
   Compiling three-d v0.15.0
   Compiling egui_backend v0.4.0
   Compiling egui_render_glow v0.4.1
   Compiling egui_window_glfw_passthrough v0.4.1
   Compiling egui_render_three_d v0.4.0
   Compiling egui_overlay v0.4.0 (/Users/test/Projects/SRCs/others/egui_overlay)
    Finished dev [unoptimized + debuginfo] target(s) in 7.77s
     Running `target/debug/examples/hello`
thread 'main' panicked at 'failed to compile vertex shader. info_log: ERROR: 0:1: '' :  version '300' is not supported
ERROR: 0:1: '' : syntax error: #version
ERROR: 0:5: 'layout' : syntax error: syntax error
', /Users/test/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui_render_glow-0.4.1/src/helpers.rs:81:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

To me it seems that this is due to usage of `egui_render_three_d`. 
It seems that it is the only option to implement EguiOverlay (as it is also stated from the Readme). 
Are there any plans to allow other options like `egui_render_wgpu` instead? @coderedart

**Comment by coderedart** [comment]
Sure. It will take like 5 min

**Comment by coderedart** [comment]
@mchaliadzinau can you test the latest commit.

**Comment by mchaliadzinau** [comment]
@coderedart it works! Thank you!

One weird thing is that I had to install `egui_render_wgpu` crate manually, 
I've tried to remove target folder and Cargo.lock completely, but it did not help.
May be `[target.'cfg(not(macos))'.dependencies]` and `[target.'cfg(macos)'.dependencies]` are not working as expected in Cargo.toml? (I see some `egui_render_three_d` in `target/debug/deps` folder)

Now it kinda works, I've commented three_d related code in hello example:
```
use egui_backend::{egui::DragValue, WindowBackend};
use egui_overlay::EguiOverlay;
use egui_render_three_d::{
    three_d::{self, ColorMaterial, Gm, Mesh},
    ThreeDBackend,
};
use egui_render_wgpu::{WgpuBackend};

fn main() {
    egui_overlay::start(HelloWorld {
        text: "hello world".to_string(),
        model: None,
    });
}

pub struct HelloWorld {
    pub text: String,
    pub model: Option<Gm<Mesh, ColorMaterial>>,
}
impl EguiOverlay for HelloWorld {
    fn gui_run(
        &mut self,
        egui_context: &egui_backend::egui::Context,
        default_gfx_backend: &mut WgpuBackend,
        glfw_backend: &mut egui_window_glfw_passthrough::GlfwBackend,
    ) {
        use three_d::*;
        // // create model if not yet created
        // self.model
            // .get_or_insert_with(|| create_triangle_model(&default_gfx_backend));
        // draw model
        if let Some(model) = &mut self.model {
            // Create a camera
            let camera = three_d::Camera::new_perspective(
                Viewport::new_at_origo(
                    glfw_backend.framebuffer_size_physical[0],
                    glfw_backend.framebuffer_size_physical[1],
                ),
                vec3(0.0, 0.0, 2.0),
                vec3(0.0, 0.0, 0.0),
                vec3(0.0, 1.0, 0.0),
                degrees(45.0),
                0.1,
                10.0,
            );
            // Update the animation of the triangle
            model.animate(glfw_backend.glfw.get_time() as _);

            // Get the screen render target to be able to render something on the screen
            // egui_render_three_d::three_d::RenderTarget::<'_>::screen(
            //     &three_d_backend.context,
            //     glfw_backend.framebuffer_size_physical[0],
            //     glfw_backend.framebuffer_size_physical[1],
            // )
            // Clear the color and depth of the screen render target. use transparent color.
            // .clear(ClearState::color_and_depth(0.0, 0.0, 0.0, 0.0, 1.0))
            // Render the triangle with the color material which uses the per vertex colors defined at construction
            // .render(&camera, std::iter::once(model), &[]);
        }
        egui_backend::egui::Window::new("hello window").show(egui_context, |ui| {
            ui.text_edit_multiline(&mut self.text);
        });

        // just some controls to show how you can use glfw_backend
        egui_backend::egui::Window::new("controls").show(egui_context, |ui| {
            // sometimes, you want to see the borders to understand where the overlay is.
            if ui.button("toggle borders").clicked() {
                let dec = glfw_backend.window.is_decorated();
                glfw_backend.window.set_decorated(!dec);
            }
            // how to change size.
            // WARNING: don't use drag value, because window size changing while dragging ui messes things up.
            let size = glfw_backend.window.get_size();
            let mut size = [size.0 as f32, size.1 as f32];
            let mut changed = false;
            ui.horizontal(|ui| {
                ui.label("width: ");
                ui.add_enabled(false, DragValue::new(&mut size[0]));
                if ui.button("inc").clicked() {
                    size[0] += 10.0;
                    changed = true;
                }
                if ui.button("dec").clicked() {
                    size[0] -= 10.0;
                    changed = true;
                }
            });
            ui.horizontal(|ui| {
                ui.label("height: ");
                ui.add_enabled(false, DragValue::new(&mut size[1]));
                if ui.button("inc").clicked() {
                    size[1] += 10.0;
                    changed = true;
                }
                if ui.button("dec").clicked() {
                    size[1] -= 10.0;
                    changed = true;
                }
            });
            if changed {
                glfw_backend.set_window_size(size);
            }
        });
        // here you decide if you want to be passthrough or not.
        if egui_context.wants_pointer_input() || egui_context.wants_keyboard_input() {
            glfw_backend.window.set_mouse_passthrough(false);
        } else {
            glfw_backend.window.set_mouse_passthrough(true);
        }
        egui_context.request_repaint();
    }
}
```
The problem now is that all background of the window is black, but it "transparent" for cursor.
```
            // Clear the color and depth of the screen render target. use transparent color.
            .clear(ClearState::color_and_depth(0.0, 0.0, 0.0, 0.0, 1.0))
```
Is following line the piece of code making overlay transparent? My initial thought was that it is for model rendering.

**Comment by coderedart** [comment]
@mchaliadzinau yeah, you need to clear the frame with a transparent color for window transparency to work. Although, the the gfx backend crates will clear the color to transparent every frame for egui i think. 

 I changed the cfg attributes in Cargo.toml in the latest commit. can you try again.

**Comment by coderedart** [comment]
Okay, i published `0.4.1` of `egui_render_wgpu`. someone with apple needs to verify if it clears the screen automatically.

**Comment by mchaliadzinau** [comment]
>I changed the cfg attributes in Cargo.toml in the latest commit. can you try again.

@coderedart with this changes it almost works :)
I believe you've also need to do this in lib.rs:
```
#[cfg(not(target_os = "macos"))]
pub use egui_render_three_d;
```

> Okay, i published 0.4.1 of egui_render_wgpu. someone with apple needs to verify if it clears the screen automatically.

Thank you. Unfortunately this did not resolve the black background issue for me. May be it is because I've commented out too much of hello example. Need to look at it more carefully.

I've also noticed following issue, but I believe it is not MacOS specific. I have two monitors setup one under another, the video is recorded from the bottom screen, it seems that this causes mismatch in coordinates. 
Btw I'm not even sure this is egui_overlay issue (and not egui), need to recheck it.
https://github.com/coderedart/egui_overlay/assets/32924456/630762b3-f878-48a8-bb08-56065e88ef86

**Comment by coderedart** [comment]
oh, i can see the problem. To make things easier, i added a new example called `basic` which should be platform neutral. 

![image](https://github.com/coderedart/egui_overlay/assets/24411704/88bd7c9e-b0c8-47ac-9598-16540514f4e7)

can you try using that example to see if your cursor position is right or wrong. When the cursor is on the bottom right corner, the position of cursor should be exactly `window size / window scale`

**Comment by mchaliadzinau** [comment]
> can you try using that example to see if your cursor position is right or wrong. When the cursor is on the bottom right corner, the position of cursor should be exactly window size / window scale

Red arrow is position of the cursor.
<img width="848" alt="Screenshot 2023-06-30 at 22 55 00" src="https://github.com/coderedart/egui_overlay/assets/32924456/c758894b-ab8f-4234-b0a0-c690892ee8c6">
<img width="632" alt="Screenshot 2023-06-30 at 22 56 04" src="https://github.com/coderedart/egui_overlay/assets/32924456/ffd56077-29fd-45e6-ae6a-462105238885">

> EDIT: apologies if my light theme in screenshot made anyone go blind. I sit right beside a window with lots of natural light, so i prefer light themes :)

Ha-ha, it is OK) But it is better to warn ppl in advance 🙈

**Comment by coderedart** [comment]
@mchaliadzinau 

It seems perfectly fine. can you try making that video like the previous one and see what is happening with the cursor position.

Also, i just pushed a new wgpu release `0.4.2` with some useful logs to help debug why your window is not transparent.

try pasting those logs here. especially the surface config and alpha mode stuff which will tell us if transparency is supported or not.

**Comment by mchaliadzinau** [comment]
@coderedart now the window is transparent!

Sorry, it is quite late here, I do not recall if I did both screenshots from the bottom screen 😅 
Here is the video, I hope it makes sense (taken from bottom screen)

https://github.com/coderedart/egui_overlay/assets/32924456/1cbe949e-4845-4d1a-b7d5-1539e088f557

Btw I do not see any logs, should I set some flag to see them?

**Comment by mchaliadzinau** [comment]
Another video w/o dragging `controls` widget:

https://github.com/coderedart/egui_overlay/assets/32924456/93525bb7-9e03-4705-9a08-ea156c335d44

**Comment by coderedart** [comment]
So, i think the problem has to do with hidpi/scale. as you can see, when the cursor is at the right border, its position is 400 (only half the width 800). Are both of your monitors different in terms of dpi?

you should see logs in terminal by default. If not, you can try `RUST_LOG=debug,wgpu=warn,naga=warn cargo run --example=basic` with the latest commit

**Comment by mchaliadzinau** [comment]
Yeah, these are different monitors, videos were recorded on Retina display, while the other display is usual one.

I agree, this issue should be closed. I can try to record videos and gather logs as you've described and then create new one.

**Comment by coderedart** [comment]
> I can try to record videos and gather logs as you've described and then create new one to address scaling issue

Yeah. Please do post the logs after moving the window between both monitors. Would be helpful to debug this issue.
